import type { GameState } from './game-state';
import { record } from './plain';
import { integer,tick,positive } from '../core/values';
import { covers } from '../world/ranges';
import { parseId } from '../core/ids/allocator';
/** Reject inconsistent transport records before any saved candidate can become live state. */
function check(condition:unknown,message:string):asserts condition {if(!condition)throw Error(message);}
/** Enforce geometry, identities, capacity, membership, phase timing and historical transfer cursors. */
export function assertTransport(s:GameState,identity:(id:string,kind:string)=>void):void {
 const members=new Set<string>(),admissions=new Set<number>();
 for(const [id,shaft] of Object.entries(s.shafts)){
 record(shaft,['id','definitionId','x','width','minFloor','maxFloor','serviceId','servedMinFloor','servedMaxFloor','stopIds','carIds','createdTick','costSinceTick','costGeneration']);identity(id,'shaft');identity(shaft.serviceId,'service');const d=s.scenario.content!.definitions.find(d=>d.typeId==='elevator.standard')!;
 for(const n of [shaft.minFloor,shaft.maxFloor,shaft.servedMinFloor,shaft.servedMaxFloor])integer(n);for(const n of [shaft.x,shaft.createdTick,shaft.costSinceTick,shaft.costGeneration])tick(n);
 check(id===shaft.id&&shaft.definitionId===d.typeId&&shaft.width===d.footprint.width&&shaft.minFloor>=s.scenario.world!.minFloor&&shaft.maxFloor<=s.scenario.world!.maxFloor&&shaft.minFloor<shaft.maxFloor&&shaft.servedMinFloor>=shaft.minFloor&&shaft.servedMaxFloor<=shaft.maxFloor&&shaft.servedMinFloor<shaft.servedMaxFloor&&shaft.createdTick<=shaft.costSinceTick&&shaft.costSinceTick<=s.clock.tick,'Invalid shaft');
 check(Array.isArray(shaft.carIds)&&shaft.carIds.length===1&&s.cars[shaft.carIds[0]]?.shaftId===id,'Shaft must own exactly one car');
 check(Array.isArray(shaft.stopIds)&&shaft.stopIds.length===shaft.servedMaxFloor-shaft.servedMinFloor+1&&shaft.stopIds.every((stopId,i)=>s.stops[stopId]?.shaftId===id&&s.stops[stopId]?.floor===shaft.servedMinFloor+i),'Noncontiguous stops');
 for(let floor=shaft.minFloor;floor<=shaft.maxFloor;floor++)check(covers(s.tower?.floors.find(f=>f.level===floor)?.constructedRanges??[],{startX:shaft.x,endXExclusive:shaft.x+shaft.width}),'Unsupported shaft reservation');
 }
 for(const [id,stop] of Object.entries(s.stops)){record(stop,['id','shaftId','serviceId','floor','anchorX2','upQueueId','downQueueId']);identity(id,'stop');const shaft=s.shafts[stop.shaftId];check(stop.id===id&&!!shaft&&shaft.serviceId===stop.serviceId&&shaft.stopIds.includes(id)&&stop.anchorX2===shaft.x*2+shaft.width,'Invalid stop');for(const [queueId,direction] of [[stop.upQueueId,'up'],[stop.downQueueId,'down']] as const){const q=s.queues[queueId];check(q?.stopId===id&&q.direction===direction&&q.serviceId===stop.serviceId,'Missing directional queue');}}
 for(const [id,queue] of Object.entries(s.queues)){
 record(queue,['id','serviceId','stopId','direction','entries']);identity(id,'queue');const stop=s.stops[queue.stopId];check(queue.id===id&&!!stop&&['up','down'].includes(queue.direction)&&id===(queue.direction==='up'?stop.upQueueId:stop.downQueueId)&&stop.serviceId===queue.serviceId&&Array.isArray(queue.entries),'Invalid queue');let previous=0;
 for(const entry of queue.entries){record(entry,['id','occupantId','tripId','unloadStopId','joinedTick','admissionSequence','reservedVisitId','lastDeniedVisitId']);identity(entry.id,'entry');tick(entry.joinedTick);positive(entry.admissionSequence);check(entry.joinedTick<=s.clock.tick&&entry.admissionSequence>previous&&entry.admissionSequence<s.ids.queueAdmission.next&&!admissions.has(entry.admissionSequence),'Invalid queue order');previous=entry.admissionSequence;admissions.add(previous);
 const p=s.occupants[entry.occupantId],to=s.stops[entry.unloadStopId];check(!!p&&p.location.kind==='queue'&&p.location.queueId===id&&p.location.entryId===entry.id&&p.tripId===entry.tripId&&s.trips[entry.tripId]?.endTick===null&&!members.has(p.id),'Invalid queue membership');members.add(p.id);check(!!to&&to.serviceId===queue.serviceId&&(to.floor-stop.floor)*(queue.direction==='up'?1:-1)>0,'Invalid unload request');
 if(entry.reservedVisitId!==null)check(Object.values(s.cars).some(c=>c.visit?.id===entry.reservedVisitId&&c.visit.boarding.some(b=>b.entryId===entry.id&&b.status==='pending')),'Missing transfer reservation');if(entry.lastDeniedVisitId!==null)check(parseId(entry.lastDeniedVisitId).kind==='visit'&&parseId(entry.lastDeniedVisitId).ordinal<s.ids.entity.next,'Invalid denial history');
 }
 }
 for(const [id,car] of Object.entries(s.cars)){
 record(car,['id','shaftId','serviceId','capacity','generation','phase','phaseStartTick','phaseDurationTicks','currentFloor','direction','targetStopId','segment','onboard','visit']);identity(id,'car');const shaft=s.shafts[car.shaftId];check(car.id===id&&!!shaft&&shaft.carIds[0]===id&&shaft.serviceId===car.serviceId&&car.capacity===8,'Invalid car ownership/capacity');tick(car.generation);tick(car.phaseStartTick);tick(car.phaseDurationTicks);integer(car.currentFloor);check(car.currentFloor>=shaft.servedMinFloor&&car.currentFloor<=shaft.servedMaxFloor&&car.phaseStartTick<=s.clock.tick&&Array.isArray(car.onboard)&&car.onboard.length<=8,'Invalid car position/load');
 const events=s.scheduledEvents.filter(e=>e.targetId===id),t=s.scenario.content!.elevatorTiming;
 const durations={starting:t.startTicks,moving:t.floorTicks,leveling:t.levelTicks,opening:t.openTicks,unloading:t.unloadTicks,boarding:t.boardTicks,dwell:t.dwellTicks,closing:t.closeTicks};
 if(car.phase==='idle')check(car.direction===null&&car.targetStopId===null&&car.segment===null&&car.visit===null&&!car.onboard.length&&events.length===0&&car.phaseDurationTicks===0,'Invalid idle car');
 else{check(Object.hasOwn(durations,car.phase)&&car.phaseDurationTicks===durations[car.phase]&&['up','down'].includes(car.direction!)&&car.targetStopId!==null&&s.stops[car.targetStopId]?.serviceId===car.serviceId,'Invalid car phase');check(events.length===1&&events[0]!.kind==='carComplete'&&events[0]!.dueTick===car.phaseStartTick+car.phaseDurationTicks,'Missing car phase completion');}
 if(car.phase==='moving'){const segment=car.segment;check(!!segment,'Missing adjacent segment');record(segment,['fromFloor','toFloor','startTick','durationTicks']);check(segment.fromFloor===car.currentFloor&&segment.toFloor===car.currentFloor+(car.direction==='up'?1:-1)&&segment.toFloor>=shaft.servedMinFloor&&segment.toFloor<=shaft.servedMaxFloor&&segment.startTick===car.phaseStartTick&&segment.durationTicks===t.floorTicks,'Invalid adjacent car segment');}else check(car.segment===null,'Unexpected moving segment');
 for(const passenger of car.onboard){record(passenger,['occupantId','unloadStopId','boardedTick']);tick(passenger.boardedTick);const p=s.occupants[passenger.occupantId],to=s.stops[passenger.unloadStopId];check(passenger.boardedTick<=s.clock.tick&&!!to&&to.serviceId===car.serviceId&&!!p&&p.location.kind==='car'&&p.location.carId===id&&p.location.unloadStopId===to.id&&!members.has(p.id),'Invalid onboard commitment');members.add(p.id);if(car.phase==='moving'||car.phase==='starting')check((to.floor-car.currentFloor)*(car.direction==='up'?1:-1)>0,'Car reverses against an onboard commitment');}
 if(['opening','unloading','boarding','dwell','closing'].includes(car.phase)){const v=car.visit;check(!!v,'Missing service visit');record(v,['id','stopId','direction','cutoffTick','unloading','unloadCursor','boarding','boardCursor']);identity(v.id,'visit');check(v.stopId===car.targetStopId&&v.direction===car.direction&&s.stops[v.stopId]?.floor===car.currentFloor&&Array.isArray(v.unloading)&&Array.isArray(v.boarding),'Invalid service visit');tick(v.unloadCursor);tick(v.boardCursor);check(v.unloadCursor<=v.unloading.length&&v.boardCursor<=v.boarding.length&&v.unloading.length<=8,'Invalid transfer cursor');
 const unloadIds=new Set<string>();for(const [index,p] of v.unloading.entries()){record(p,['occupantId','unloadStopId','boardedTick']);check(!unloadIds.has(p.occupantId)&&p.unloadStopId===v.stopId&&parseId(p.occupantId).ordinal<s.ids.entity.next,'Invalid unloading cohort');unloadIds.add(p.occupantId);if(index>=v.unloadCursor)check(car.onboard.some(o=>o.occupantId===p.occupantId&&o.unloadStopId===p.unloadStopId),'Lost pending unload');}
 const rowIds=new Set<string>();let last=0;for(const [index,row] of v.boarding.entries()){record(row,['entryId','occupantId','unloadStopId','admissionSequence','status']);check(!rowIds.has(row.entryId)&&row.admissionSequence>last&&row.admissionSequence<s.ids.queueAdmission.next&&['pending','boarded','denied','canceled'].includes(row.status),'Invalid boarding cohort');rowIds.add(row.entryId);last=row.admissionSequence;if(row.status==='pending'){check(index>=v.boardCursor&&Object.values(s.queues).some(q=>q.entries.some(e=>e.id===row.entryId&&e.occupantId===row.occupantId&&e.unloadStopId===row.unloadStopId&&e.reservedVisitId===v.id)),'Lost pending boarding');}}
 if(v.cutoffTick!==null){tick(v.cutoffTick);check(v.cutoffTick<=s.clock.tick&&v.unloadCursor===v.unloading.length,'Boarding before unloading');}else check(v.boarding.length===0&&v.boardCursor===0,'Missing boarding cutoff');
 if(car.phase==='unloading')check(v.unloadCursor<v.unloading.length,'No pending unloading transfer');if(car.phase==='boarding')check(v.cutoffTick!==null&&v.boardCursor<v.boarding.length&&['pending','canceled'].includes(v.boarding[v.boardCursor]!.status),'No pending boarding transfer');
 }else check(car.visit===null,'Unexpected service visit');
 }
}
