import type { GameState } from './game-state';
import type { DayEvidence } from '../progression/day-evidence';
import { progressionPredicates } from '../progression/evaluate';
import { record } from './plain';
import { integer,tick } from '../core/values';
/** Reject unknown evidence fields and impossible daily bounds without filling missing saved counters. */
function evidence(e:DayEvidence,s:GameState):void {record(e,['dayStart','eligibleFullDay','minAccessibleLeasedOffices','minAssignedWorkers','restaurantAccessibleEvidence','admittedRestaurantVisits','completedOfficeArrivals']);for(const [key,value] of Object.entries(e))if(key!=='eligibleFullDay')tick(value as number);if(e.dayStart%s.scenario.dayTicks!==0||e.dayStart>s.clock.tick||e.eligibleFullDay!==(e.dayStart>=s.scenario.initialTick))throw Error('Invalid full-day evidence');const c=s.scenario.content;if(c){const capacity=c.definitions.find(d=>d.typeId==='office.small')!.capacity;if(e.minAssignedWorkers>c.officeMarketWorkers||e.completedOfficeArrivals>c.officeMarketWorkers||BigInt(e.minAccessibleLeasedOffices)*BigInt(capacity)!==BigInt(e.minAssignedWorkers))throw Error('Progression exceeds or disagrees with whole-office workforce');}}
/** Validate permanent award chronology and the completed-day report references used to explain it. */
export function assertProgression(s:GameState):void {const p=s.progression;record(p,['level','awardedTick','dayEvidence','lastEvaluation']);evidence(p.dayEvidence,s);if(p.dayEvidence.dayStart!==s.clock.lastDayBoundaryTick||![1,2].includes(p.level)||(p.level===1)!==(p.awardedTick===null))throw Error('Invalid progression state');if(p.awardedTick!==null){tick(p.awardedTick);if(p.awardedTick%s.scenario.dayTicks!==0||p.awardedTick<=s.scenario.dayTicks||p.awardedTick>s.clock.tick)throw Error('Invalid award tick');}
 const v=p.lastEvaluation;if(v===null){if(s.scenario.content&&s.clock.lastDayBoundaryTick>0)throw Error('Missing evaluation');return;}
 record(v,['day','evidence','cashMinor','operatingNetMinor','quality','samples','strandedCount','unresolvedPriorDayTrips']);evidence(v.evidence,s);for(const n of [v.day,v.samples,v.strandedCount,v.unresolvedPriorDayTrips])tick(n);integer(v.cashMinor);integer(v.operatingNetMinor);const report=s.transportReports.daily.at(-1),finance=s.economy.operatingDays.find(d=>d.day===v.day);if(v.day!==s.clock.lastDayBoundaryTick/s.scenario.dayTicks-1||v.evidence.dayStart!==v.day*s.scenario.dayTicks||!report||report.day!==v.day||v.samples!==report.samples||v.quality!==report.quality||v.operatingNetMinor!==finance?.netMinor)throw Error('Invalid progression report references');if(s.scenario.content){const met=progressionPredicates(v,s.scenario.content.level2).every(x=>x.met);if(met&&p.level!==2)throw Error('Missing earned award');if(p.awardedTick===s.clock.lastDayBoundaryTick&&!met)throw Error('Award contradicts its completed-day evidence');}}
