import { restaurantAmounts } from '../../simulation/economy/settlement';
import { restaurantDefinition } from '../../simulation/facilities/restaurants';
import { accessQuery } from './access-queries';
import { workforceQuery } from './workforce-queries';
import type { GameState } from '../../simulation';
import { officeDefinition } from '../../simulation/facilities/offices';
import { availableMarket,vacancyReason } from '../../simulation/demand/office-leasing';
import { accruedAmounts } from '../../simulation/economy/accrual';
import { freezeDeep } from '../../simulation/state/plain';
/** Expose tenancy, actual attendance, access and finance as separate immutable inspector facts. */
export function inspectOffice(state:GameState,id:string){const o=state.offices[id];if(!o)return null;const d=officeDefinition(state),access=accessQuery(state,id)!;return freezeDeep({workforce:workforceQuery(state,id),id:o.id,floor:o.floor,x:o.x,width:o.width,tenancy:o.lease?'leased':'vacant',tenantId:o.lease?.tenantId??null,assigned:o.lease?.assignedWorkerIds.length??0,present:(o.lease?.assignedWorkerIds??[]).filter(id=>{const p=state.occupants[id];return p?.location.kind==='facility'&&p.location.facilityId===o.id;}).length,access,vacancyReason:vacancyReason(state,o),rentSuspended:!!o.lease&&!access.accessible,rentMinorPerDay:d.rentMinorPerDay,operatingMinorPerDay:d.operatingMinorPerDay,accrued:accruedAmounts(state,o),recentIncomeMinor:state.economy.transactions.filter(t=>t.source.startsWith(`office:${id}:`)&&t.amountMinor>0&&t.atTick>state.clock.tick-state.scenario.dayTicks).reduce((n,t)=>n+t.amountMinor,0),availableMarket:availableMarket(state),nextReviewTick:state.clock.initialReviewPending?state.clock.tick:state.scenario.initialTick+(Math.floor((state.clock.tick-state.scenario.initialTick)/state.scenario.dayTicks)+1)*state.scenario.dayTicks});}
export type OfficeInspection=NonNullable<ReturnType<typeof inspectOffice>>;

/** Keep allocated requests, physical travelers, indoor guests and earned admission income distinct. */
export function inspectRestaurant(state:GameState,id:string){const r=state.restaurants[id];if(!r)return null;const day=Math.floor(state.clock.tick/state.scenario.dayTicks),allocation=state.restaurantDays.find(d=>d.day===day),visits=allocation?.visits.filter(v=>v.facilityId===id)??[],d=restaurantDefinition(state);return freezeDeep({id:r.id,floor:r.floor,x:r.x,width:r.width,expected:visits.length,remaining:visits.filter(v=>v.status==='scheduled').length,incoming:state.restaurantDays.flatMap(d=>d.visits).filter(v=>v.facilityId===id&&v.status==='traveling').length,inside:Object.values(state.occupants).filter(p=>p.kind==='customer'&&p.location.kind==='facility'&&p.location.facilityId===id).length,visits:r.visits,revenueMinor:r.revenueMinor,todayVisits:visits.filter(v=>v.admittedTick!==null).length,access:accessQuery(state,id)!,accrued:restaurantAmounts(state,r),operatingMinorPerDay:d.operatingMinorPerDay,visitPriceMinor:d.visitPriceMinor,allowance:state.scenario.content!.restaurantDailyCustomers,nextReviewTick:state.clock.initialReviewPending?state.clock.tick:state.scenario.initialTick+(Math.floor((state.clock.tick-state.scenario.initialTick)/state.scenario.dayTicks)+1)*state.scenario.dayTicks,meal:state.scenario.content!.schedules.restaurant,awaitingReview:!allocation?.allocations.some(a=>a.facilityId===id)});}
