import { createHash } from 'node:crypto';
import expected from '../fixtures/congestion-comparison-expected.json';
import { GameSession } from '../../src/app/game/session';
import { encodeState,decodeState } from '../../src/simulation';
import { expect,it } from 'vitest';
import { congestion,observeRush } from '../fixtures/congestion';
import { elevator } from '../fixtures/transport';
import { captureState } from '../../src/simulation';
it('additional affordable eight-person cars improve the entire identical cohort by the mandatory thresholds',()=>{const start=congestion();expect(createHash('sha256').update(encodeState(start)).digest('hex')).toBe(expected.fixtureHash);const a=captureState(start),b=captureState(start);elevator(b,5,14);expect(b.workforceDays).toEqual(a.workforceDays);expect(b.rng).toEqual(a.rng);expect(b.occupants).toEqual(a.occupants);expect(Object.values(b.offices).map(({accrual,...office})=>office)).toEqual(Object.values(a.offices).map(({accrual,...office})=>office));expect(b.scenario).toEqual(a.scenario);const baseline=observeRush(a),improved=observeRush(b);expect(baseline.maxWait).toBeGreaterThanOrEqual(600);expect(baseline.maxDenials).toBeGreaterThanOrEqual(2);expect(baseline.report.completed).toBe(96);expect(improved.report.completed).toBe(96);expect(improved.report.memberIds).toEqual(baseline.report.memberIds);expect(improved.report.meanWaitingTicks!).toBeLessThanOrEqual(baseline.report.meanWaitingTicks!*.7);expect(improved.peak).toBeLessThanOrEqual(baseline.peak*.7);expect(improved.report.quality!).toBeGreaterThanOrEqual(baseline.report.quality!+10);expect(improved.cars).toHaveLength(2);expect(baseline).toEqual(expected.baseline);expect(improved).toEqual(expected.improved);},30000);

/** Replay the unchanged cohort through real application pacing, including pauses and segmented frames. */
it.each([1,4,8] as const)('retains the full comparison under %sx application pacing and pauses',speed=>{for(const improved of [false,true]){const start=congestion();if(improved){elevator(start,5,14);}const target=improved?expected.improved:expected.baseline;const direct=decodeState(encodeState(start));observeRush(direct);let now=0;const session=new GameSession({state:start},{now:()=>now,requestFrame:()=>0,cancelFrame:()=>{}},{start:()=>()=>{}});session.setSpeed(speed);session.frame(now);let frames=0;while(session.hud().tick<target.lastArrivalTick){now+=Math.max(0.001,Math.min(17,(target.lastArrivalTick-session.hud().tick)*1000/(120*speed)));session.frame(now);if(session.error)throw Error(session.error);if(++frames%97===0){session.setSpeed(0);const before=encodeState(session.capture());now+=500;session.frame(now);expect(encodeState(session.capture())).toBe(before);session.setSpeed(speed);}}expect(encodeState(session.capture())).toBe(encodeState(direct));session.dispose();}},60000);
