import { test,expect } from 'vitest';
import { passengerAtPhase } from '../fixtures/one-elevator-passenger';
import { command,until } from '../fixtures/one-worker';
import { captureState } from '../../src/simulation';
import { resolveCars } from '../../src/simulation/transportation/elevators/car';
test.each(['leveling','boarding','moving','unloading'] as const)('an unrelated topology edit during %s preserves unload intent and finishes with walking',phase=>{const {s,id}=passengerAtPhase(phase);expect(command(s,{kind:'placeFacility',payload:{definitionId:'office.small',floor:0,x:40}}).ok).toBe(true);captureState(s);until(s,s.clock.tick+1200);expect(s.occupants[id]!.state).toBe('insideFacility');expect(Object.values(s.trips).find(t=>t.occupantId===id)!.transferCount).toBe(0);captureState(s);});
test('a canceled empty reposition finishes its committed adjacent segment before idling',()=>{const {s,id,carId}=passengerAtPhase('leveling'),car=s.cars[carId]!,start=s.clock.tick;
 // Controller-only fixture: the empty car rests at the valid upper landing while the real passenger waits below.
 car.currentFloor=3;car.phase='idle';car.phaseDurationTicks=0;car.direction=null;car.targetStopId=null;s.scheduledEvents=s.scheduledEvents.filter(e=>e.targetId!==carId);resolveCars(s);captureState(s);expect(s.cars[carId]!.phase).toBe('starting');until(s,start+3);expect(s.cars[carId]!.segment).toMatchObject({fromFloor:3,toFloor:2});expect(command(s,{kind:'demolishEntity',payload:{entityId:Object.keys(s.offices)[0]!}}).ok).toBe(true);expect(s.occupants[id]!.goal.kind).toBe('exit');captureState(s);until(s,start+5);expect(s.cars[carId]!.phase).toBe('moving');until(s,start+6);expect(s.cars[carId]).toMatchObject({phase:'idle',currentFloor:2,direction:null,segment:null});expect(s.scheduledEvents.some(e=>e.targetId===carId)).toBe(false);captureState(s);});
test('removing an empty shaft with a waiting passenger cancels membership and preserves a real exit',()=>{const {s,id,carId}=passengerAtPhase('leveling'),shaft=s.cars[carId]!.shaftId;expect(command(s,{kind:'demolishEntity',payload:{entityId:shaft}}).ok).toBe(true);expect(s.occupants[id]!.goal.kind).toBe('exit');expect(Object.values(s.queues)).toHaveLength(0);captureState(s);until(s,s.clock.tick+1000);expect(s.occupants[id]!.state).toBe('outside');});
