import { test,expect } from 'vitest';
import { oneElevatorPassenger,passengerAtPhase } from '../fixtures/one-elevator-passenger';
import { arrival } from '../fixtures/transport';
import { until,command } from '../fixtures/one-worker';
import { captureState,advance,rebuildDerived } from '../../src/simulation';
test('one passenger walks, requests, boards, rides, unloads and enters the upper office',()=>{const s=oneElevatorPassenger(),id=arrival(s),q=s.occupants[id]!.schedule!,carId=Object.keys(s.cars)[0]!,states=new Set<string>(),phases=new Set<string>();for(let t=s.clock.tick;t<q.arrivalTick+1000;t++){until(s,t);states.add(s.occupants[id]!.state);phases.add(s.cars[carId]!.phase);if(s.occupants[id]!.state==='insideFacility')break;}expect([...states]).toEqual(expect.arrayContaining(['walking','waitingForElevator','ridingElevator','insideFacility']));expect([...phases]).toEqual(expect.arrayContaining(['idle','leveling','opening','boarding','dwell','closing','starting','moving','unloading']));const trip=Object.values(s.trips)[0]!;expect(trip.outcome).toBe('completed');expect(trip.totals.walking).toBeGreaterThan(0);expect(trip.totals.waiting).toBeGreaterThan(0);expect(trip.totals.riding).toBeGreaterThan(0);expect(trip.transferCount).toBe(1);expect(s.cars[carId]!.capacity).toBe(8);captureState(s);until(s,q.departureTick+1000);expect(s.occupants[id]!.state).toBe('outside');});
test.each(['moving','boarding','unloading'] as const)('capture/rebuild in %s preserves the entire following day and frozen pause',phase=>{const {s,id,carId}=passengerAtPhase(phase),copy=captureState(s);rebuildDerived(copy);expect(advance(s,0).ok).toBe(true);expect(s).toEqual(copy);if(phase!=='boarding'){const shaft=s.cars[carId]!.shaftId;expect(command(s,{kind:'demolishEntity',payload:{entityId:shaft}}).code).toBe('loadedCar');copy.lastCommandSequence=s.lastCommandSequence;expect(command(s,{kind:'setElevatorServiceRange',payload:{shaftId:shaft,minFloor:0,maxFloor:2}}).code).toBe('loadedCar');copy.lastCommandSequence=s.lastCommandSequence;}until(s,s.clock.tick+86400);until(copy,copy.clock.tick+86400);expect(copy).toEqual(s);expect(s.occupants[id]).toBeDefined();captureState(s);});

test('normal, fast, very-fast and segmented advancement preserve identical full-day transport state',()=>{const initial=oneElevatorPassenger(),a=captureState(initial),b=captureState(initial),c=captureState(initial);until(a,86400);for(const [state,size] of [[b,480],[c,960]] as const)while(state.clock.tick<86400){expect(advance(state,0).ok).toBe(true);until(state,Math.min(state.clock.tick+size,86400));}expect(b).toEqual(a);expect(c).toEqual(a);});
