import { expect,it,vi } from 'vitest';
import { GameSession } from '../../src/app/game/session';
import { SaveGame } from '../../src/app/game/save-game';
import { loadGame } from '../../src/app/game/load-game';
import { MemorySaveRepository } from '../fixtures/save-repository';
import { oneWorker } from '../fixtures/one-worker';
import { encodeState } from '../../src/simulation';
/** Create a paused session whose frame callbacks and wall clock are entirely controlled. */
function setup(){let now=0;const callbacks:((t:number)=>void)[]=[];const session=new GameSession({state:oneWorker()},{now:()=>now,requestFrame:()=>0,cancelFrame:()=>{}},{start:cb=>{callbacks.push(cb);return ()=>{};}});session.start(()=>{});const repository=new MemorySaveRepository();return {session,repository,saver:new SaveGame(session,repository),callbacks,setNow:(n:number)=>{now=n;}};}
it('captures detached revision/tick and serializes writes while paused edits remain dirty',async()=>{const {session,repository,saver}=setup();let commit!:()=>void;repository.gate=new Promise(resolve=>{commit=resolve;});const before=session.capture();const a=saver.save();session.dispatch({kind:'placeFacility',payload:{definitionId:'office.small',floor:0,x:48}});const b=saver.save();await Promise.resolve();await Promise.resolve();expect(repository.writes).toBe(1);expect(session.hud().unsaved).toBe(true);commit();await a;expect(session.hud().unsaved).toBe(true);expect((repository.slot as {state:unknown}).state).toEqual(before);await b;expect(repository.writes).toBe(2);expect(session.hud().unsaved).toBe(false);});
it('preserves previous committed slot on failed replacement and retries successfully',async()=>{const {session,repository,saver}=setup();await saver.save();const previous=structuredClone(repository.slot);session.dispatch({kind:'placeFacility',payload:{definitionId:'office.small',floor:0,x:48}});repository.fail=true;await expect(saver.save()).rejects.toThrow('Quota');expect(repository.slot).toEqual(previous);expect(session.hud().unsaved).toBe(true);repository.fail=false;await saver.save();expect(session.hud().unsaved).toBe(false);});
it('validates before prompting and cancellation changes neither live state nor storage',async()=>{const {session,repository,saver}=setup();await saver.save();session.dispatch({kind:'placeFacility',payload:{definitionId:'office.small',floor:0,x:48}});const before=encodeState(session.capture()),confirm=vi.fn(async()=>false),valid=repository.slot;repository.slot={broken:true};await expect(loadGame(session,repository,confirm)).rejects.toThrow();expect(confirm).not.toHaveBeenCalled();repository.slot=valid;expect(await loadGame(session,repository,confirm)).toBe('canceled');expect(encodeState(session.capture())).toBe(before);expect(repository.slot).toEqual(valid);expect(repository.writes).toBe(1);});
it('ignores old-generation completion and leaves New Game dirty without writing its state',async()=>{const {session,repository,saver}=setup();let commit!:()=>void;repository.gate=new Promise(resolve=>{commit=resolve;});const pending=saver.save();session.replace({state:oneWorker()},true);commit();expect((await pending).current).toBe(false);expect(session.hud().unsaved).toBe(true);});
it('loads paused with cleared debt, no offline time, and no stale callback ownership',async()=>{const {session,repository,saver,callbacks,setNow}=setup();await saver.save();const tick=session.hud().tick,old=callbacks[0]!;session.setSpeed(8);session.frame(0);setNow(10000);session.frame(10000);expect(session.pacingStatus().debt).toBeGreaterThan(0);expect(await loadGame(session,repository,async()=>true)).toBe('loaded');expect(session.pacingStatus().debt).toBe(0);expect(session.hud().speed).toBe(0);expect(session.hud().tick).toBe(tick);expect(callbacks).toHaveLength(2);session.setSpeed(1);old(999999);expect(session.hud().tick).toBe(tick);expect(session.hud().unsaved).toBe(false);});
it('rechecks paused edits made while confirmation was pending',async()=>{const {session,repository,saver}=setup();await saver.save();session.dispatch({kind:'placeFacility',payload:{definitionId:'office.small',floor:0,x:48}});let calls=0;expect(await loadGame(session,repository,async()=>{calls++;if(calls===1){session.dispatch({kind:'placeFacility',payload:{definitionId:'office.small',floor:0,x:72}});return true;}return false;})).toBe('canceled');expect(calls).toBe(2);expect(Object.keys(session.capture().offices)).toHaveLength(3);});
it.each(['replace','dispose'] as const)('ignores a candidate whose read completed after %s',async action=>{const {session,repository,saver}=setup();await saver.save();let complete!:(value:unknown)=>void;const read=vi.spyOn(repository,'read').mockImplementation(()=>new Promise(resolve=>{complete=resolve;})),confirm=vi.fn(async()=>true);const pending=loadGame(session,repository,confirm);if(action==='replace')session.replace({state:oneWorker()},true);else session.dispose();const after=encodeState(session.capture());complete(repository.slot);expect(await pending).toBe('stale');expect(confirm).not.toHaveBeenCalled();expect(encodeState(session.capture())).toBe(after);read.mockRestore();});
it('continues playing during a detached save without attributing later ticks to the committed revision',async()=>{const {session,repository,saver,setNow}=setup();let commit!:()=>void;repository.gate=new Promise(resolve=>{commit=resolve;});const pending=saver.save();session.setSpeed(1);session.frame(0);setNow(1000);session.frame(1000);commit();const result=await pending;expect(result.tick).toBe(21600);expect(session.hud().tick).toBe(21720);expect(session.hud().unsaved).toBe(true);});
import { createKernelState } from '../../src/simulation';
import { createSaveEnvelope } from '../../src/simulation/state/save-envelope';
import { KERNEL_SCENARIO,SEEDS } from '../fixtures/seeds';
it('rejects a valid kernel-only envelope before showing a player replacement choice',async()=>{const {session,repository}=setup(),before=encodeState(session.capture()),confirm=vi.fn(async()=>true);repository.slot=createSaveEnvelope(createKernelState(KERNEL_SCENARIO,SEEDS[0]));await expect(loadGame(session,repository,confirm)).rejects.toThrow('playable tower');expect(confirm).not.toHaveBeenCalled();expect(encodeState(session.capture())).toBe(before);});
