import { expect,it } from 'vitest';
import { GameSession } from '../../src/app/game/session';
import { createGame,encodeState } from '../../src/simulation';
import { createSaveEnvelope,validateSaveEnvelope } from '../../src/simulation/state/save-envelope';
import { MVP_DEFAULT } from '../../src/content/scenarios/mvp-default';
import { SEEDS } from '../fixtures/seeds';
import { command,place,until } from '../fixtures/one-worker';
import { elevator } from '../fixtures/transport';
/** Build a finite mixed replay fixture with real workers/customers and unchanged movement/economy/progression rules. */
function start(seed:string){const scenario={...MVP_DEFAULT,scenarioId:'three-day-mixed-replay',content:{...MVP_DEFAULT.content,officeMarketWorkers:12,restaurantDailyCustomers:4,definitions:MVP_DEFAULT.content.definitions.map(d=>d.typeId==='office.small'?{...d,capacity:4}:d)}};const s=createGame(scenario,seed);for(let floor=1;floor<=3;floor++){command(s,{kind:'constructFloorRange',payload:{floor,startX:0,endXExclusive:48}});place(s,24,floor);}elevator(s,3,10);command(s,{kind:'placeFacility',payload:{definitionId:'restaurant.small',floor:0,x:24}});return s;}
for(const seed of SEEDS)it(`replays three complete days at 30/60/120 FPS, all speeds, pauses and persisted splits: ${seed}`,()=>{const initial=start(seed),targets=[50000,86400,129600,172800,216000,259200,280800],direct=validateSaveEnvelope(createSaveEnvelope(initial)).state;const expected=new Map<number,string>();for(const target of targets){until(direct,target);command(direct,{kind:'setElevatorServiceRange',payload:{shaftId:Object.keys(direct.shafts)[0]!,minFloor:0,maxFloor:3}});expected.set(target,encodeState(direct));}
 for(const fps of [30,60,120]){let now=0,frames=0;const session=new GameSession({state:initial},{now:()=>now,requestFrame:()=>0,cancelFrame:()=>{}},{start:()=>()=>{}});for(const [i,target] of targets.entries()){const speed=([1,4,8] as const)[i%3]!;session.setSpeed(speed);while(session.hud().tick<target){const remaining=target-session.hud().tick-session.pacingStatus().debt;now+=Math.max(.001,Math.min(1000/fps,remaining*1000/(120*speed)));session.frame(now);if(session.error)throw Error(session.error);if(++frames%997===0){session.setSpeed(0);const before=session.hud().tick;now+=3000;session.frame(now);expect(session.hud().tick).toBe(before);session.setSpeed(speed);}}session.dispatch({kind:'setElevatorServiceRange',payload:{shaftId:Object.keys(initial.shafts)[0]!,minFloor:0,maxFloor:3}});expect(encodeState(session.capture())).toBe(expected.get(target));const saved=validateSaveEnvelope(JSON.parse(JSON.stringify(createSaveEnvelope(session.capture()))));session.replace({state:saved.state},true);expect(session.hud().speed).toBe(0);expect(session.pacingStatus().debt).toBe(0);}session.dispose();}
},120000);
