import { it,expect,vi } from 'vitest';
import { IndexedDbSaveRepository } from '../../src/persistence/indexeddb-save-repository';
import { createSaveEnvelope } from '../../src/simulation/state/save-envelope';
import { oneWorker } from '../fixtures/one-worker';
/** Expose request and transaction events independently; this fixture tests ordering, not native durability. */
function fake(){const request:any={},open:any={},tx:any={objectStore:()=>({put:vi.fn(()=>request),get:()=>request,getAll:()=>request})},db:any={close:vi.fn(),objectStoreNames:{contains:()=>true},transaction:vi.fn(()=>tx)};open.result=db;const factory={open:vi.fn(()=>open)} as unknown as IDBFactory;return {request,open,tx,db,repo:new IndexedDbSaveRepository(()=>factory)};}
/** Deliver connection success and allow the adapter to synchronously install its transaction handlers. */
async function connected(f:ReturnType<typeof fake>){f.open.onsuccess();await Promise.resolve();await Promise.resolve();}
it('does not acknowledge request success; transaction complete alone publishes success',async()=>{const f=fake(),done=vi.fn(),pending=f.repo.write('local-main',createSaveEnvelope(oneWorker())).then(done);await connected(f);f.request.result='local-main';f.request.onsuccess();await Promise.resolve();expect(done).not.toHaveBeenCalled();f.tx.oncomplete();await pending;expect(done).toHaveBeenCalledOnce();expect(f.db.close).toHaveBeenCalledOnce();});
it('rejects transaction abort after successful put and permits subsequent retry',async()=>{const f=fake(),pending=f.repo.write('local-main',createSaveEnvelope(oneWorker()));await connected(f);f.request.onsuccess();f.tx.error=Error('Quota exceeded');f.tx.onabort();await expect(pending).rejects.toThrow('Quota');expect(f.db.close).toHaveBeenCalledOnce();});
it('reports blocked upgrades and closes late open results and version-changing connections',async()=>{const f=fake(),pending=f.repo.read('local-main');f.open.onblocked();await expect(pending).rejects.toThrow('blocked');f.open.onsuccess();expect(f.db.close).toHaveBeenCalledOnce();const g=fake(),read=g.repo.read('local-main');await connected(g);g.db.onversionchange();expect(g.db.close).toHaveBeenCalledOnce();g.request.result=undefined;g.request.onsuccess();g.tx.oncomplete();expect(await read).toBeNull();});
it('validates before opening and reports unavailable storage',async()=>{const f=fake(),bad=createSaveEnvelope(oneWorker());bad.metadata.savedTick++;await expect(f.repo.write('local-main',bad)).rejects.toThrow();expect(f.open.onsuccess).toBeUndefined();await expect(new IndexedDbSaveRepository(()=>{throw Error('Unavailable');}).read('local-main')).rejects.toThrow('Unavailable');});
