import { test,expect } from 'vitest';
import { passengerAtPhase } from '../fixtures/one-elevator-passenger';
import { until,command } from '../fixtures/one-worker';
import { captureState,validateState } from '../../src/simulation';
test('boarding retains queue membership until one tick completes, then atomically occupies one car slot',()=>{const {s,id,carId}=passengerAtPhase('boarding'),car=s.cars[carId]!,visit=car.visit!;expect(car.onboard).toHaveLength(0);expect(s.occupants[id]!.state).toBe('waitingForElevator');expect(visit.boarding[0]!.status).toBe('pending');expect(visit.cutoffTick).toBe(s.clock.tick);captureState(s);until(s,s.clock.tick+1);expect(s.occupants[id]!.state).toBe('ridingElevator');expect(s.cars[carId]!.onboard).toHaveLength(1);expect(Object.values(s.queues).flatMap(q=>q.entries)).toHaveLength(0);expect(s.cars[carId]!.visit!.boarding[0]!.status).toBe('boarded');captureState(s);});
test('unloading completes after one tick and keeps the processed cohort as historical data',()=>{const {s,id,carId}=passengerAtPhase('unloading'),start=s.clock.tick;expect(s.occupants[id]!.state).toBe('ridingElevator');until(s,start+1);const car=s.cars[carId]!;expect(s.occupants[id]!.state).toBe('walking');expect(car.onboard).toHaveLength(0);expect(car.visit!.unloading).toHaveLength(1);expect(car.visit!.unloadCursor).toBe(1);expect(car.visit!.cutoffTick).toBe(start+1);captureState(s);});
test('removing an office during a reserved transfer cancels boarding safely without changing cutoff',()=>{const {s,id,carId}=passengerAtPhase('boarding'),cutoff=s.cars[carId]!.visit!.cutoffTick;expect(command(s,{kind:'demolishEntity',payload:{entityId:Object.keys(s.offices)[0]!}}).ok).toBe(true);expect(s.cars[carId]!.visit!.boarding[0]!.status).toBe('canceled');captureState(s);until(s,s.clock.tick+1);expect(s.cars[carId]!.onboard).toHaveLength(0);expect(s.cars[carId]!.visit!.cutoffTick).toBe(cutoff);expect(s.occupants[id]!.goal.kind).toBe('exit');});
test('snapshot validation rejects broken capacity, duplicate membership and altered movement',()=>{const {s,carId}=passengerAtPhase('moving');for(const edit of [(bad:any)=>bad.cars[carId].capacity=9,(bad:any)=>bad.cars[carId].onboard.push({...bad.cars[carId].onboard[0]}),(bad:any)=>bad.cars[carId].segment.toFloor=3,(bad:any)=>bad.scheduledEvents=bad.scheduledEvents.filter((e:any)=>e.kind!=='carComplete')]){const bad=captureState(s);edit(bad);expect(validateState(bad).ok).toBe(false);}});

test('saved future routes reject deleted stairs, altered endpoint continuity and changed origin preference',()=>{const {s,id}=passengerAtPhase('idle');for(const edit of [(bad:any)=>bad.occupants[id].journey.preference='stairs',(bad:any)=>bad.occupants[id].journey.legs[0].unloadStopId='stop:999',(bad:any)=>bad.occupants[id].journey.legs[0].from.x2=100,(bad:any)=>bad.occupants[id].journey.legs.push({kind:'stair',stairId:'stair:999',from:{floor:3,x2:64},to:{floor:4,x2:64},durationTicks:30})]){const bad=captureState(s);edit(bad);expect(validateState(bad).ok).toBe(false);}});
