import type { SaveRepository } from '../../../src/app/ports/save-repository';
import { IndexedDbSaveRepository } from '../../../src/persistence/indexeddb-save-repository';
import type { SaveEnvelope } from '../../../src/simulation/state/save-envelope';
import { validateSaveEnvelope } from '../../../src/simulation/state/save-envelope';
/** Exercise an actual aborted replacement after native request success; ordinary reads use the real adapter. */
export class AbortingNativeRepository implements SaveRepository {private repository=new IndexedDbSaveRepository();
 /** Read the previous committed slot through the production adapter after an aborted replacement. */
 read(slotId:string){return this.repository.read(slotId);}
 /** Expose production metadata reads without changing slot contents. */
 listMetadata(){return this.repository.listMetadata();}
 /** Deliberately abort a successful put inside its native transaction, so rollback remains a browser responsibility. */
 async write(slotId:string,envelope:SaveEnvelope):Promise<void>{const candidate=validateSaveEnvelope(envelope,slotId);return new Promise((resolve,reject)=>{const open=indexedDB.open('TowerSimSaves',1);open.onupgradeneeded=()=>{if(!open.result.objectStoreNames.contains('saves'))open.result.createObjectStore('saves');};open.onerror=()=>reject(open.error);open.onblocked=()=>reject(Error('Storage exercise blocked'));open.onsuccess=()=>{const db=open.result;db.onversionchange=()=>db.close();const tx=db.transaction('saves','readwrite');tx.objectStore('saves').put(candidate,slotId).onsuccess=()=>tx.abort();tx.onabort=()=>{db.close();reject(Error('Native test aborted replacement after request success'));};tx.oncomplete=()=>{db.close();resolve();};};});}}

/** Measure user-action-to-visible-result latency in the fixture harness, excluding time spent deciding in a load dialog. */
export function observeNativeStorage(root:HTMLElement):void {const output=document.createElement('p');output.setAttribute('aria-label','Native storage measurements');output.textContent='Native storage measurements: no operation recorded.';root.after(output);let pending:{kind:'Save'|'Load';start:number;waitingSince:number|null}|null=null;root.addEventListener('click',event=>{const button=(event.target as Element).closest('button');if(!button)return;const text=button.textContent;if(text==='Save'||text==='Load')pending={kind:text,start:performance.now(),waitingSince:null};else if(text==='Discard unsaved progress & load'&&pending){if(pending.waitingSince!==null)pending.start+=performance.now()-pending.waitingSince;pending.waitingSince=null;}else if(text==='Cancel load')pending=null;},true);new MutationObserver(()=>{if(!pending)return;if(pending.kind==='Load'&&pending.waitingSince===null&&root.querySelector('dialog[open]'))pending.waitingSince=performance.now();const message=[...root.querySelectorAll('[role="status"]')].map(n=>n.textContent??'').find(text=>text.startsWith(pending!.kind==='Save'?'Saved tick ':'Loaded tick ')||text.startsWith(`${pending!.kind} failed:`));if(!message)return;output.textContent=`Native storage measurements: ${pending.kind} ${(performance.now()-pending.start).toFixed(1)} ms. ${message}`;pending=null;}).observe(root,{childList:true,subtree:true,characterData:true});}
